#项目信息
spring:
  application:
    name: TLBook

  #数据库信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TLBook?serverTimezone=UTC
    password: root
    username: root
server:
  port: 80
#MyBatis配置信息
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

#Sa-Token配置信息
sa-token:
  token-name: cwsya
  timeout: -1
  activity-timeout: 600
  is-concurrent: false
  is-share: false
  token-style: uuid
  is-log: true

#腾讯cos整合测试
COS:
  #key
  secretId: AKIDmPoytZdDASUHvLcR7XnpdCVZNvIcqV4N
  secretKey: DBuNhneFbhgQuFLBl6C8oGbgojX5NPBi
  appId: 1256545590
  #存储桶
  bucketName: cwsya-1256545590
  #区域设置
  region: ap-hongkong
  #域名
  url: https://cwsya-1256545590.cos.ap-hongkong.myqcloud.com
  #默认文件夹
  prefix: cws/
